# Generated by Django 5.0.4 on 2024-04-08 21:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("climato", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poste",
            name="changed_at",
        ),
        migrations.RemoveField(
            model_name="poste",
            name="changed_by",
        ),
        migrations.RemoveField(
            model_name="poste",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="poste",
            name="created_by",
        ),
    ]
